"""
Git hook generators — creates pre-commit and commit-msg hook scripts.
"""
import os
import stat


PRE_COMMIT_HOOK = """#!/bin/sh
# Auto-generated by gitwf — checks for common issues before commit

# Check for debug statements
echo "Checking for debug statements..."
if git diff --cached --name-only --diff-filter=ACM | xargs grep -l 'import pdb\\|debugger\\|console\\.log\\|print(' 2>/dev/null; then
    echo "WARNING: Debug statements found in staged files"
fi

# Check for large files (>1MB)
echo "Checking file sizes..."
large_files=$(git diff --cached --name-only --diff-filter=ACM | while read f; do
    size=$(wc -c < "$f" 2>/dev/null || echo 0)
    if [ "$size" -gt 1048576 ]; then
        echo "$f ($size bytes)"
    fi
done)
if [ -n "$large_files" ]; then
    echo "ERROR: Large files detected:"
    echo "$large_files"
    exit 1
fi

echo "Pre-commit checks passed"
"""

COMMIT_MSG_HOOK = """#!/bin/sh
# Auto-generated by gitwf — validates conventional commit format

commit_msg=$(cat "$1")
pattern='^(feat|fix|docs|style|refactor|test|chore|perf|ci)(\\(.+\\))?!?:.+$'

if ! echo "$commit_msg" | head -1 | grep -qE "$pattern"; then
    echo "ERROR: Commit message does not follow conventional format"
    echo "Expected: <type>(<scope>): <description>"
    echo "Types: feat, fix, docs, style, refactor, test, chore, perf, ci"
    echo ""
    echo "Your message: $commit_msg"
    exit 1
fi

# Check subject length
subject_len=$(echo "$commit_msg" | head -1 | wc -c)
if [ "$subject_len" -gt 72 ]; then
    echo "ERROR: Commit subject too long ($subject_len > 72 chars)"
    exit 1
fi

echo "Commit message validated"
"""


class HookManager:
    def __init__(self, repo_path: str = "."):
        self.hooks_dir = os.path.join(repo_path, ".git", "hooks")

    def install_pre_commit(self) -> str:
        return self._write_hook("pre-commit", PRE_COMMIT_HOOK)

    def install_commit_msg(self) -> str:
        return self._write_hook("commit-msg", COMMIT_MSG_HOOK)

    def install_all(self) -> list[str]:
        return [self.install_pre_commit(), self.install_commit_msg()]

    def _write_hook(self, name: str, content: str) -> str:
        path = os.path.join(self.hooks_dir, name)
        os.makedirs(self.hooks_dir, exist_ok=True)
        with open(path, "w", newline="\n") as f:
            f.write(content)
        os.chmod(path, os.stat(path).st_mode | stat.S_IEXEC)
        return path

    def list_installed(self) -> list[str]:
        if not os.path.exists(self.hooks_dir):
            return []
        hooks = []
        for name in ["pre-commit", "commit-msg", "pre-push"]:
            path = os.path.join(self.hooks_dir, name)
            if os.path.exists(path):
                hooks.append(name)
        return hooks
